name: Second workflow
on: push
jobs:
    test_project:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4.1.1
            - name: Setup .NET
              uses: actions/setup-dotnet@v4.0.0
              with:
                dotnet-version: '8'
            - name: Install dependencies
              run: dotnet restore
            - name: Build app
              run: dotnet build --no-restore
            - name: Print Message
              run: echo "Running tests now..."
            - name: Run test
              run: dotnet test
    print_success_message:
        runs-on: ubuntu_latest
        needs: test_project
        steps:
            - name: Print successmessage
              run: echo "Tests succesful"